# Generated by Django 5.2.6 on 2025-09-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='year',
        ),
        migrations.AddField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publications/'),
        ),
        migrations.AddField(
            model_name='publication',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
