# Generated by Django 5.2.6 on 2025-09-09 01:55

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0003_remove_publication_year_publication_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated list of tags (e.g., HCI, ICT)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
