# Generated by Django 5.2.6 on 2025-09-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0004_publication_date_publication_journal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
