# Generated by Django 5.2.6 on 2025-09-09 02:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0005_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(blank=True, help_text='Comma-separated list of languages (e.g., Python, JavaScript)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
