# Generated by Django 5.2.6 on 2025-09-09 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0007_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+\\d{1,13}$', message='Enter a valid WhatsApp number with country code (e.g., +12025550123)')])),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
