# Generated by Django 5.2.6 on 2025-09-09 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0008_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, help_text='URL to Facebook profile', null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True, help_text='URL to Instagram profile', null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, help_text='URL to LinkedIn profile', null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, help_text='URL to Twitter profile', null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
