# Generated by Django 5.2.6 on 2025-09-09 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0009_profile_facebook_profile_instagram_profile_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload a PDF resume (e.g., resume.pdf)', null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, help_text='URL to Facebook profile (e.g., https://facebook.com/nasim.promise03)', null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True, help_text='URL to Instagram profile (e.g., https://instagram.com/username)', null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, help_text='URL to LinkedIn profile (e.g., https://linkedin.com/in/username)', null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, help_text='URL to Twitter profile (e.g., https://twitter.com/username)', null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
