# Generated by Django 5.2.6 on 2025-09-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0010_profile_resume_alter_profile_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
